package fifo

// NOT THREAD SAFE
// FIFO cache (i.e. always evicts oldest)
// Fully generated by an LLM, but reviewed by a human.
type Cache[K comparable, V any] interface {
	Get(key K) (val V, found bool)
	Put(key K, value V)
	Size() int
}

func New[K comparable, V any](capacity int) Cache[K, V] {
	return newCache[K, V](capacity)
}
