import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The sidebar is explicit rather than autogenerated: ordering lives here
// instead of in per-file `sidebar_position`
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        description:
          'Follow this 10 quick steps guide to learn the most important Twigg concepts, from creating your repository to submitting your first commit.',
      },
      items: [
        'tutorial/Installation',
        'tutorial/create-repository',
        'tutorial/clone-repository',
        'tutorial/create-a-commit',
        'tutorial/push-your-commit',
        'tutorial/review-your-commit',
        'tutorial/fix-your-commit',
        'tutorial/resolve-comments',
        'tutorial/submit-your-commit',
        'tutorial/pull',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'commit-stacking',
        'wip-commits',
        'resolving-conflicts',
        'owners-lgtm',
        'import-from-github',
        {
          type: 'category',
          label: 'Git Mirror',
          link: {type: 'doc', id: 'git-mirror/git-mirror'},
          items: [
            'git-mirror/github',
            'git-mirror/gitlab',
            'git-mirror/other',
          ],
        },
        'vs-code-extension',
      ],
    },
    {
      type: 'category',
      label: 'CLI reference',
      // The slug is pinned: docs link to `../commands`.
      link: {
        type: 'generated-index',
        slug: '/commands',
        description:
          'Twigg was designed to have as few, simple commands as possible - yet allow you to do everything you need.',
      },
      items: [
        'commands/commit-syntax',
        'commands/commit',
        'commands/push',
        'commands/pull',
        'commands/init',
        'commands/rebase',
        'commands/amend',
        'commands/restore',
        'commands/load',
        'commands/key',
        'commands/server',
        'commands/ci-list',
      ],
    },
    {
      type: 'category',
      label: 'CI/CD',
      link: {type: 'doc', id: 'ci-cd/ci-cd'},
      items: [
        'ci-cd/ci-json-reference',
        'ci-cd/cd-json-reference',
        'ci-cd/concurrency-and-plans',
      ],
    },
  ],
};

export default sidebars;
